# Generated by Django 5.2.3 on 2025-06-27 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "invoice_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("received_date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbounds_core",
                        to="core.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplied_inbounds_core",
                        to="core.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("so_reference", models.CharField(blank=True, max_length=100)),
                ("dispatch_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "delivery_note_file",
                    models.FileField(
                        blank=True, null=True, upload_to="delivery_notes/"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_customers_core",
                        to="core.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbounds_core",
                        to="core.product",
                    ),
                ),
            ],
        ),
    ]
