# Generated by Django 5.2.3 on 2025-06-26 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='date',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='inbound',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inbound',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inbound',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='delivery_note_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_notes/'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='dispatch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outbound',
            name='so_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
