# Generated by Django 5.2.3 on 2025-06-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("operator", "Operator"),
                ],
                default="Operator",
                max_length=20,
            ),
        ),
    ]
