# Generated by Django 5.2.3 on 2025-06-27 11:19

import core.models.stock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='dispatch_date',
            field=models.DateField(default=core.models.stock.get_current_date),
        ),
    ]
