# Generated by Django 5.2.3 on 2025-06-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_outbound_dispatch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Webhook name for identification', max_length=100)),
                ('url', models.URLField(help_text='Webhook endpoint URL')),
                ('webhook_type', models.CharField(choices=[('inventory_threshold', 'Inventory Threshold Breach'), ('bulk_upload', 'Bulk Upload Success'), ('inbound_created', 'Inbound Created'), ('outbound_created', 'Outbound Created'), ('batch_expiring', 'Batch Expiring Soon'), ('batch_expired', 'Batch Expired')], help_text='Type of event to trigger webhook', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook is active')),
                ('secret_key', models.CharField(blank=True, help_text='Secret key for webhook signature', max_length=255)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Additional headers to send with webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inbound',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Batch identifier for tracking', max_length=100),
        ),
        migrations.AddField(
            model_name='inbound',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for this batch', null=True),
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='Unique batch identifier', max_length=100)),
                ('quantity', models.IntegerField(default=0, help_text='Current quantity in this batch')),
                ('initial_quantity', models.IntegerField(default=0, help_text='Initial quantity when batch was created')),
                ('expiry_date', models.DateField(help_text='Expiry date for this batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.product')),
            ],
            options={
                'ordering': ['expiry_date', 'created_at'],
                'unique_together': {('product', 'batch_id')},
            },
        ),
    ]
